class BladeRunner {

    public static void main(String[] args) {

        System.out.println("Main Started");

        Blade blade1 = new Blade();
        blade1.bladeId = 1;
        blade1.brand = "Gillette";
        blade1.bladeType = "Twin Blade";
        blade1.material = "Stainless Steel";
        blade1.price = 49.99;
        blade1.isDisposable = true;
        blade1.usage = "Shaving";
        System.out.println("=== Blade 1 ===");
        System.out.println("ID: " + blade1.bladeId);
        System.out.println("Brand: " + blade1.brand);
        System.out.println("Type: " + blade1.bladeType);
        System.out.println("Material: " + blade1.material);
        System.out.println("Price: ₹" + blade1.price);
        System.out.println("Disposable: " + blade1.isDisposable);
        System.out.println("Usage: " + blade1.usage);

        Blade blade2 = new Blade();
        blade2.bladeId = 2;
        blade2.brand = "SuperMax";
        blade2.bladeType = "Triple Blade";
        blade2.material = "Carbon Steel";
        blade2.price = 59.00;
        blade2.isDisposable = false;
        blade2.usage = "Shaving";
        System.out.println("=== Blade 2 ===");
        System.out.println("ID: " + blade2.bladeId);
        System.out.println("Brand: " + blade2.brand);
        System.out.println("Type: " + blade2.bladeType);
        System.out.println("Material: " + blade2.material);
        System.out.println("Price: ₹" + blade2.price);
        System.out.println("Disposable: " + blade2.isDisposable);
        System.out.println("Usage: " + blade2.usage);

        Blade blade3 = new Blade();
        blade3.bladeId = 3;
        blade3.brand = "Wilkinson Sword";
        blade3.bladeType = "Single Blade";
        blade3.material = "Titanium";
        blade3.price = 39.00;
        blade3.isDisposable = true;
        blade3.usage = "Shaving";
        System.out.println("=== Blade 3 ===");
        System.out.println("ID: " + blade3.bladeId);
        System.out.println("Brand: " + blade3.brand);
        System.out.println("Type: " + blade3.bladeType);
        System.out.println("Material: " + blade3.material);
        System.out.println("Price: ₹" + blade3.price);
        System.out.println("Disposable: " + blade3.isDisposable);
        System.out.println("Usage: " + blade3.usage);

        Blade blade4 = new Blade();
        blade4.bladeId = 4;
        blade4.brand = "Dorco";
        blade4.bladeType = "Five Blade";
        blade4.material = "Steel";
        blade4.price = 69.0;
        blade4.isDisposable = false;
        blade4.usage = "Shaving";
        System.out.println("=== Blade 4 ===");
        System.out.println("ID: " + blade4.bladeId);
        System.out.println("Brand: " + blade4.brand);
        System.out.println("Type: " + blade4.bladeType);
        System.out.println("Material: " + blade4.material);
        System.out.println("Price: ₹" + blade4.price);
        System.out.println("Disposable: " + blade4.isDisposable);
        System.out.println("Usage: " + blade4.usage);

        Blade blade5 = new Blade();
        blade5.bladeId = 5;
        blade5.brand = "Feather";
        blade5.bladeType = "Double Edge";
        blade5.material = "Platinum";
        blade5.price = 89.0;
        blade5.isDisposable = false;
        blade5.usage = "Shaving";
        System.out.println("=== Blade 5 ===");
        System.out.println("ID: " + blade5.bladeId);
        System.out.println("Brand: " + blade5.brand);
        System.out.println("Type: " + blade5.bladeType);
        System.out.println("Material: " + blade5.material);
        System.out.println("Price: ₹" + blade5.price);
        System.out.println("Disposable: " + blade5.isDisposable);
        System.out.println("Usage: " + blade5.usage);

        Blade blade6 = new Blade();
        blade6.bladeId = 6;
        blade6.brand = "Bic";
        blade6.bladeType = "Disposable";
        blade6.material = "Plastic + Steel";
        blade6.price = 29.99;
        blade6.isDisposable = true;
        blade6.usage = "Shaving";
        System.out.println("=== Blade 6 ===");
        System.out.println("ID: " + blade6.bladeId);
        System.out.println("Brand: " + blade6.brand);
        System.out.println("Type: " + blade6.bladeType);
        System.out.println("Material: " + blade6.material);
        System.out.println("Price: ₹" + blade6.price);
        System.out.println("Disposable: " + blade6.isDisposable);
        System.out.println("Usage: " + blade6.usage);

        Blade blade7 = new Blade();
        blade7.bladeId = 7;
        blade7.brand = "Dollar";
        blade7.bladeType = "Single Blade";
        blade7.material = "Steel";
        blade7.price = 19.0;
        blade7.isDisposable = true;
        blade7.usage = "Shaving";
        System.out.println("=== Blade 7 ===");
        System.out.println("ID: " + blade7.bladeId);
        System.out.println("Brand: " + blade7.brand);
        System.out.println("Type: " + blade7.bladeType);
        System.out.println("Material: " + blade7.material);
        System.out.println("Price: ₹" + blade7.price);
        System.out.println("Disposable: " + blade7.isDisposable);
        System.out.println("Usage: " + blade7.usage);

        Blade blade8 = new Blade();
        blade8.bladeId = 8;
        blade8.brand = "Laser";
        blade8.bladeType = "Double Edge";
        blade8.material = "Stainless Steel";
        blade8.price = 45.0;
        blade8.isDisposable = false;
        blade8.usage = "Shaving";
        System.out.println("=== Blade 8 ===");
        System.out.println("ID: " + blade8.bladeId);
        System.out.println("Brand: " + blade8.brand);
        System.out.println("Type: " + blade8.bladeType);
        System.out.println("Material: " + blade8.material);
        System.out.println("Price: ₹" + blade8.price);
        System.out.println("Disposable: " + blade8.isDisposable);
        System.out.println("Usage: " + blade8.usage);

        Blade blade9 = new Blade();
        blade9.bladeId = 9;
        blade9.brand = "RazoRock";
        blade9.bladeType = "Premium";
        blade9.material = "Titanium";
        blade9.price = 99.0;
        blade9.isDisposable = false;
        blade9.usage = "Luxury Shaving";
        System.out.println("=== Blade 9 ===");
        System.out.println("ID: " + blade9.bladeId);
        System.out.println("Brand: " + blade9.brand);
        System.out.println("Type: " + blade9.bladeType);
        System.out.println("Material: " + blade9.material);
        System.out.println("Price: ₹" + blade9.price);
        System.out.println("Disposable: " + blade9.isDisposable);
        System.out.println("Usage: " + blade9.usage);

        Blade blade10 = new Blade();
        blade10.bladeId = 10;
        blade10.brand = "Shavette";
        blade10.bladeType = "Barber Blade";
        blade10.material = "Carbon Steel";
        blade10.price = 75.5;
        blade10.isDisposable = true;
        blade10.usage = "Professional Use";
        System.out.println("=== Blade 10 ===");
        System.out.println("ID: " + blade10.bladeId);
        System.out.println("Brand: " + blade10.brand);
        System.out.println("Type: " + blade10.bladeType);
        System.out.println("Material: " + blade10.material);
        System.out.println("Price: ₹" + blade10.price);
        System.out.println("Disposable: " + blade10.isDisposable);
        System.out.println("Usage: " + blade10.usage);

        Blade blade11 = new Blade();
        blade11.bladeId = 11;
        blade11.brand = "Merkur";
        blade11.bladeType = "German Steel";
        blade11.material = "Steel";
        blade11.price = 109.0;
        blade11.isDisposable = false;
        blade11.usage = "Shaving";
        System.out.println("=== Blade 11 ===");
        System.out.println("ID: " + blade11.bladeId);
        System.out.println("Brand: " + blade11.brand);
        System.out.println("Type: " + blade11.bladeType);
        System.out.println("Material: " + blade11.material);
        System.out.println("Price: ₹" + blade11.price);
        System.out.println("Disposable: " + blade11.isDisposable);
        System.out.println("Usage: " + blade11.usage);

        Blade blade12 = new Blade();
        blade12.bladeId = 12;
        blade12.brand = "Persona";
        blade12.bladeType = "Chrome";
        blade12.material = "Alloy Steel";
        blade12.price = 92.0;
        blade12.isDisposable = false;
        blade12.usage = "Shaving";
        System.out.println("=== Blade 12 ===");
        System.out.println("ID: " + blade12.bladeId);
        System.out.println("Brand: " + blade12.brand);
        System.out.println("Type: " + blade12.bladeType);
        System.out.println("Material: " + blade12.material);
        System.out.println("Price: ₹" + blade12.price);
        System.out.println("Disposable: " + blade12.isDisposable);
        System.out.println("Usage: " + blade12.usage);

        Blade blade13 = new Blade();
        blade13.bladeId = 13;
        blade13.brand = "Parker";
        blade13.bladeType = "Sharp Edge";
        blade13.material = "Carbon Alloy";
        blade13.price = 88.5;
        blade13.isDisposable = false;
        blade13.usage = "Shaving";
        System.out.println("=== Blade 13 ===");
        System.out.println("ID: " + blade13.bladeId);
        System.out.println("Brand: " + blade13.brand);
        System.out.println("Type: " + blade13.bladeType);
        System.out.println("Material: " + blade13.material);
        System.out.println("Price: ₹" + blade13.price);
        System.out.println("Disposable: " + blade13.isDisposable);
        System.out.println("Usage: " + blade13.usage);

        Blade blade14 = new Blade();
        blade14.bladeId = 14;
        blade14.brand = "Derby";
        blade14.bladeType = "Swedish Steel";
        blade14.material = "Stainless Steel";
        blade14.price = 67.0;
        blade14.isDisposable = true;
        blade14.usage = "Shaving";
        System.out.println("=== Blade 14 ===");
        System.out.println("ID: " + blade14.bladeId);
        System.out.println("Brand: " + blade14.brand);
        System.out.println("Type: " + blade14.bladeType);
        System.out.println("Material: " + blade14.material);
        System.out.println("Price: ₹" + blade14.price);
        System.out.println("Disposable: " + blade14.isDisposable);
        System.out.println("Usage: " + blade14.usage);

        Blade blade15 = new Blade();
        blade15.bladeId = 15;
        blade15.brand = "Treet";
        blade15.bladeType = "Classic";
        blade15.material = "Steel";
        blade15.price = 59.0;
        blade15.isDisposable = false;
        blade15.usage = "Shaving";
        System.out.println("=== Blade 15 ===");
        System.out.println("ID: " + blade15.bladeId);
        System.out.println("Brand: " + blade15.brand);
        System.out.println("Type: " + blade15.bladeType);
        System.out.println("Material: " + blade15.material);
        System.out.println("Price: ₹" + blade15.price);
        System.out.println("Disposable: " + blade15.isDisposable);
        System.out.println("Usage: " + blade15.usage);

        Blade blade16 = new Blade();
        blade16.bladeId = 16;
        blade16.brand = "Kai";
        blade16.bladeType = "Japanese Edge";
        blade16.material = "Titanium";
        blade16.price = 129.0;
        blade16.isDisposable = false;
        blade16.usage = "Shaving";
        System.out.println("=== Blade 16 ===");
        System.out.println("ID: " + blade16.bladeId);
        System.out.println("Brand: " + blade16.brand);
        System.out.println("Type: " + blade16.bladeType);
        System.out.println("Material: " + blade16.material);
        System.out.println("Price: ₹" + blade16.price);
        System.out.println("Disposable: " + blade16.isDisposable);
        System.out.println("Usage: " + blade16.usage);

        Blade blade17 = new Blade();
        blade17.bladeId = 17;
        blade17.brand = "Astra";
        blade17.bladeType = "Superior Platinum";
        blade17.material = "Platinum";
        blade17.price = 99.0;
        blade17.isDisposable = false;
        blade17.usage = "Shaving";
        System.out.println("=== Blade 17 ===");
        System.out.println("ID: " + blade17.bladeId);
        System.out.println("Brand: " + blade17.brand);
        System.out.println("Type: " + blade17.bladeType);
        System.out.println("Material: " + blade17.material);
        System.out.println("Price: ₹" + blade17.price);
        System.out.println("Disposable: " + blade17.isDisposable);
        System.out.println("Usage: " + blade17.usage);

        Blade blade18 = new Blade();
        blade18.bladeId = 18;
        blade18.brand = "Croma";
        blade18.bladeType = "Budget";
        blade18.material = "Plastic";
        blade18.price = 12.0;
        blade18.isDisposable = true;
        blade18.usage = "Disposable Shaving";
        System.out.println("=== Blade 18 ===");
        System.out.println("ID: " + blade18.bladeId);
        System.out.println("Brand: " + blade18.brand);
        System.out.println("Type: " + blade18.bladeType);
        System.out.println("Material: " + blade18.material);
        System.out.println("Price: ₹" + blade18.price);
        System.out.println("Disposable: " + blade18.isDisposable);
        System.out.println("Usage: " + blade18.usage);

        Blade blade19 = new Blade();
        blade19.bladeId = 19;
        blade19.brand = "Harry's";
        blade19.bladeType = "Precision";
        blade19.material = "Steel";
        blade19.price = 85.0;
        blade19.isDisposable = false;
        blade19.usage = "Shaving";
        System.out.println("=== Blade 19 ===");
        System.out.println("ID: " + blade19.bladeId);
        System.out.println("Brand: " + blade19.brand);
        System.out.println("Type: " + blade19.bladeType);
        System.out.println("Material: " + blade19.material);
        System.out.println("Price: ₹" + blade19.price);
        System.out.println("Disposable: " + blade19.isDisposable);
        System.out.println("Usage: " + blade19.usage);

        Blade blade20 = new Blade();
        blade20.bladeId = 20;
        blade20.brand = "Dollar";
        blade20.bladeType = "Budget";
        blade20.material = "Carbon";
        blade20.price = 20.0;
        blade20.isDisposable = true;
        blade20.usage = "Quick Shave";
        System.out.println("=== Blade 20 ===");
        System.out.println("ID: " + blade20.bladeId);
        System.out.println("Brand: " + blade20.brand);
        System.out.println("Type: " + blade20.bladeType);
        System.out.println("Material: " + blade20.material);
        System.out.println("Price: ₹" + blade20.price);
        System.out.println("Disposable: " + blade20.isDisposable);
        System.out.println("Usage: " + blade20.usage);

        System.out.println("Main Ended");
    }
}
