class GymEquipmentRunner {

    public static void main(String[] args) {

        System.out.println("Main Started");

        GymEquipment equipment1 = new GymEquipment();
        equipment1.equipmentId = 1;
        equipment1.name = "Treadmill";
        equipment1.brand = "FitTech";
        equipment1.category = "Cardio";
        equipment1.weight = 80.5;
        equipment1.price = 55000.0;
        equipment1.isElectric = true;
        System.out.println("=== Equipment 1 ===");
        System.out.println("ID: " + equipment1.equipmentId);
        System.out.println("Name: " + equipment1.name);
        System.out.println("Brand: " + equipment1.brand);
        System.out.println("Category: " + equipment1.category);
        System.out.println("Weight: " + equipment1.weight);
        System.out.println("Price: ₹" + equipment1.price);
        System.out.println("Electric: " + equipment1.isElectric);

        GymEquipment equipment2 = new GymEquipment();
        equipment2.equipmentId = 2;
        equipment2.name = "Elliptical";
        equipment2.brand = "HealthMax";
        equipment2.category = "Cardio";
        equipment2.weight = 65.0;
        equipment2.price = 48000.0;
        equipment2.isElectric = true;
        System.out.println("=== Equipment 2 ===");
        System.out.println("ID: " + equipment2.equipmentId);
        System.out.println("Name: " + equipment2.name);
        System.out.println("Brand: " + equipment2.brand);
        System.out.println("Category: " + equipment2.category);
        System.out.println("Weight: " + equipment2.weight);
        System.out.println("Price: ₹" + equipment2.price);
        System.out.println("Electric: " + equipment2.isElectric);

        GymEquipment equipment3 = new GymEquipment();
        equipment3.equipmentId = 3;
        equipment3.name = "Dumbbell Set";
        equipment3.brand = "IronGrip";
        equipment3.category = "Strength";
        equipment3.weight = 20.0;
        equipment3.price = 3200.0;
        equipment3.isElectric = false;
        System.out.println("=== Equipment 3 ===");
        System.out.println("ID: " + equipment3.equipmentId);
        System.out.println("Name: " + equipment3.name);
        System.out.println("Brand: " + equipment3.brand);
        System.out.println("Category: " + equipment3.category);
        System.out.println("Weight: " + equipment3.weight);
        System.out.println("Price: ₹" + equipment3.price);
        System.out.println("Electric: " + equipment3.isElectric);

        GymEquipment equipment4 = new GymEquipment();
        equipment4.equipmentId = 4;
        equipment4.name = "Bench Press";
        equipment4.brand = "MuscleCraft";
        equipment4.category = "Strength";
        equipment4.weight = 30.0;
        equipment4.price = 6500.0;
        equipment4.isElectric = false;
        System.out.println("=== Equipment 4 ===");
        System.out.println("ID: " + equipment4.equipmentId);
        System.out.println("Name: " + equipment4.name);
        System.out.println("Brand: " + equipment4.brand);
        System.out.println("Category: " + equipment4.category);
        System.out.println("Weight: " + equipment4.weight);
        System.out.println("Price: ₹" + equipment4.price);
        System.out.println("Electric: " + equipment4.isElectric);

        GymEquipment equipment5 = new GymEquipment();
        equipment5.equipmentId = 5;
        equipment5.name = "Rowing Machine";
        equipment5.brand = "EnduroFit";
        equipment5.category = "Cardio";
        equipment5.weight = 55.0;
        equipment5.price = 42000.0;
        equipment5.isElectric = true;
        System.out.println("=== Equipment 5 ===");
        System.out.println("ID: " + equipment5.equipmentId);
        System.out.println("Name: " + equipment5.name);
        System.out.println("Brand: " + equipment5.brand);
        System.out.println("Category: " + equipment5.category);
        System.out.println("Weight: " + equipment5.weight);
        System.out.println("Price: ₹" + equipment5.price);
        System.out.println("Electric: " + equipment5.isElectric);

		        GymEquipment equipment6 = new GymEquipment();
        equipment6.equipmentId = 6;
        equipment6.name = "Kettlebell";
        equipment6.brand = "IronZone";
        equipment6.category = "Strength";
        equipment6.weight = 12.0;
        equipment6.price = 1800.0;
        equipment6.isElectric = false;
        System.out.println("=== Equipment 6 ===");
        System.out.println("ID: " + equipment6.equipmentId);
        System.out.println("Name: " + equipment6.name);
        System.out.println("Brand: " + equipment6.brand);
        System.out.println("Category: " + equipment6.category);
        System.out.println("Weight: " + equipment6.weight);
        System.out.println("Price: ₹" + equipment6.price);
        System.out.println("Electric: " + equipment6.isElectric);

        GymEquipment equipment7 = new GymEquipment();
        equipment7.equipmentId = 7;
        equipment7.name = "Stationary Bike";
        equipment7.brand = "CardioFit";
        equipment7.category = "Cardio";
        equipment7.weight = 45.0;
        equipment7.price = 37000.0;
        equipment7.isElectric = true;
        System.out.println("=== Equipment 7 ===");
        System.out.println("ID: " + equipment7.equipmentId);
        System.out.println("Name: " + equipment7.name);
        System.out.println("Brand: " + equipment7.brand);
        System.out.println("Category: " + equipment7.category);
        System.out.println("Weight: " + equipment7.weight);
        System.out.println("Price: ₹" + equipment7.price);
        System.out.println("Electric: " + equipment7.isElectric);

        GymEquipment equipment8 = new GymEquipment();
        equipment8.equipmentId = 8;
        equipment8.name = "Barbell";
        equipment8.brand = "ProBar";
        equipment8.category = "Strength";
        equipment8.weight = 25.0;
        equipment8.price = 3000.0;
        equipment8.isElectric = false;
        System.out.println("=== Equipment 8 ===");
        System.out.println("ID: " + equipment8.equipmentId);
        System.out.println("Name: " + equipment8.name);
        System.out.println("Brand: " + equipment8.brand);
        System.out.println("Category: " + equipment8.category);
        System.out.println("Weight: " + equipment8.weight);
        System.out.println("Price: ₹" + equipment8.price);
        System.out.println("Electric: " + equipment8.isElectric);

        GymEquipment equipment9 = new GymEquipment();
        equipment9.equipmentId = 9;
        equipment9.name = "Power Rack";
        equipment9.brand = "StrengthX";
        equipment9.category = "Strength";
        equipment9.weight = 70.0;
        equipment9.price = 25000.0;
        equipment9.isElectric = false;
        System.out.println("=== Equipment 9 ===");
        System.out.println("ID: " + equipment9.equipmentId);
        System.out.println("Name: " + equipment9.name);
        System.out.println("Brand: " + equipment9.brand);
        System.out.println("Category: " + equipment9.category);
        System.out.println("Weight: " + equipment9.weight);
        System.out.println("Price: ₹" + equipment9.price);
        System.out.println("Electric: " + equipment9.isElectric);

        GymEquipment equipment10 = new GymEquipment();
        equipment10.equipmentId = 10;
        equipment10.name = "Leg Press";
        equipment10.brand = "LegZone";
        equipment10.category = "Strength";
        equipment10.weight = 65.0;
        equipment10.price = 30000.0;
        equipment10.isElectric = false;
        System.out.println("=== Equipment 10 ===");
        System.out.println("ID: " + equipment10.equipmentId);
        System.out.println("Name: " + equipment10.name);
        System.out.println("Brand: " + equipment10.brand);
        System.out.println("Category: " + equipment10.category);
        System.out.println("Weight: " + equipment10.weight);
        System.out.println("Price: ₹" + equipment10.price);
        System.out.println("Electric: " + equipment10.isElectric);

        GymEquipment equipment11 = new GymEquipment();
        equipment11.equipmentId = 11;
        equipment11.name = "Cross Trainer";
        equipment11.brand = "Aerofit";
        equipment11.category = "Cardio";
        equipment11.weight = 60.0;
        equipment11.price = 44000.0;
        equipment11.isElectric = true;
        System.out.println("=== Equipment 11 ===");
        System.out.println("ID: " + equipment11.equipmentId);
        System.out.println("Name: " + equipment11.name);
        System.out.println("Brand: " + equipment11.brand);
        System.out.println("Category: " + equipment11.category);
        System.out.println("Weight: " + equipment11.weight);
        System.out.println("Price: ₹" + equipment11.price);
        System.out.println("Electric: " + equipment11.isElectric);

        GymEquipment equipment12 = new GymEquipment();
        equipment12.equipmentId = 12;
        equipment12.name = "Chest Press";
        equipment12.brand = "MuscleFit";
        equipment12.category = "Strength";
        equipment12.weight = 55.0;
        equipment12.price = 27000.0;
        equipment12.isElectric = false;
        System.out.println("=== Equipment 12 ===");
        System.out.println("ID: " + equipment12.equipmentId);
        System.out.println("Name: " + equipment12.name);
        System.out.println("Brand: " + equipment12.brand);
        System.out.println("Category: " + equipment12.category);
        System.out.println("Weight: " + equipment12.weight);
        System.out.println("Price: ₹" + equipment12.price);
        System.out.println("Electric: " + equipment12.isElectric);

        GymEquipment equipment13 = new GymEquipment();
        equipment13.equipmentId = 13;
        equipment13.name = "Smith Machine";
        equipment13.brand = "FitSmith";
        equipment13.category = "Strength";
        equipment13.weight = 75.0;
        equipment13.price = 35000.0;
        equipment13.isElectric = false;
        System.out.println("=== Equipment 13 ===");
        System.out.println("ID: " + equipment13.equipmentId);
        System.out.println("Name: " + equipment13.name);
        System.out.println("Brand: " + equipment13.brand);
        System.out.println("Category: " + equipment13.category);
        System.out.println("Weight: " + equipment13.weight);
        System.out.println("Price: ₹" + equipment13.price);
        System.out.println("Electric: " + equipment13.isElectric);

        GymEquipment equipment14 = new GymEquipment();
        equipment14.equipmentId = 14;
        equipment14.name = "Ab Machine";
        equipment14.brand = "CoreFlex";
        equipment14.category = "Strength";
        equipment14.weight = 40.0;
        equipment14.price = 15000.0;
        equipment14.isElectric = false;
        System.out.println("=== Equipment 14 ===");
        System.out.println("ID: " + equipment14.equipmentId);
        System.out.println("Name: " + equipment14.name);
        System.out.println("Brand: " + equipment14.brand);
        System.out.println("Category: " + equipment14.category);
        System.out.println("Weight: " + equipment14.weight);
        System.out.println("Price: ₹" + equipment14.price);
        System.out.println("Electric: " + equipment14.isElectric);

        GymEquipment equipment15 = new GymEquipment();
        equipment15.equipmentId = 15;
        equipment15.name = "Lat Pulldown";
        equipment15.brand = "StrongPull";
        equipment15.category = "Strength";
        equipment15.weight = 50.0;
        equipment15.price = 22000.0;
        equipment15.isElectric = false;
        System.out.println("=== Equipment 15 ===");
        System.out.println("ID: " + equipment15.equipmentId);
        System.out.println("Name: " + equipment15.name);
        System.out.println("Brand: " + equipment15.brand);
        System.out.println("Category: " + equipment15.category);
        System.out.println("Weight: " + equipment15.weight);
        System.out.println("Price: ₹" + equipment15.price);
        System.out.println("Electric: " + equipment15.isElectric);

        GymEquipment equipment16 = new GymEquipment();
        equipment16.equipmentId = 16;
        equipment16.name = "Pull-Up Bar";
        equipment16.brand = "BarZone";
        equipment16.category = "Strength";
        equipment16.weight = 8.0;
        equipment16.price = 3000.0;
        equipment16.isElectric = false;
        System.out.println("=== Equipment 16 ===");
        System.out.println("ID: " + equipment16.equipmentId);
        System.out.println("Name: " + equipment16.name);
        System.out.println("Brand: " + equipment16.brand);
        System.out.println("Category: " + equipment16.category);
        System.out.println("Weight: " + equipment16.weight);
        System.out.println("Price: ₹" + equipment16.price);
        System.out.println("Electric: " + equipment16.isElectric);

        GymEquipment equipment17 = new GymEquipment();
        equipment17.equipmentId = 17;
        equipment17.name = "Dip Station";
        equipment17.brand = "StrongCore";
        equipment17.category = "Strength";
        equipment17.weight = 15.0;
        equipment17.price = 5000.0;
        equipment17.isElectric = false;
        System.out.println("=== Equipment 17 ===");
        System.out.println("ID: " + equipment17.equipmentId);
        System.out.println("Name: " + equipment17.name);
        System.out.println("Brand: " + equipment17.brand);
        System.out.println("Category: " + equipment17.category);
        System.out.println("Weight: " + equipment17.weight);
        System.out.println("Price: ₹" + equipment17.price);
        System.out.println("Electric: " + equipment17.isElectric);

        GymEquipment equipment18 = new GymEquipment();
        equipment18.equipmentId = 18;
        equipment18.name = "Cable Crossover";
        equipment18.brand = "CableX";
        equipment18.category = "Strength";
        equipment18.weight = 60.0;
        equipment18.price = 28000.0;
        equipment18.isElectric = false;
        System.out.println("=== Equipment 18 ===");
        System.out.println("ID: " + equipment18.equipmentId);
        System.out.println("Name: " + equipment18.name);
        System.out.println("Brand: " + equipment18.brand);
        System.out.println("Category: " + equipment18.category);
        System.out.println("Weight: " + equipment18.weight);
        System.out.println("Price: ₹" + equipment18.price);
        System.out.println("Electric: " + equipment18.isElectric);

        GymEquipment equipment19 = new GymEquipment();
        equipment19.equipmentId = 19;
        equipment19.name = "Preacher Curl Bench";
        equipment19.brand = "ArmFlex";
        equipment19.category = "Strength";
        equipment19.weight = 25.0;
        equipment19.price = 8000.0;
        equipment19.isElectric = false;
        System.out.println("=== Equipment 19 ===");
        System.out.println("ID: " + equipment19.equipmentId);
        System.out.println("Name: " + equipment19.name);
        System.out.println("Brand: " + equipment19.brand);
        System.out.println("Category: " + equipment19.category);
        System.out.println("Weight: " + equipment19.weight);
        System.out.println("Price: ₹" + equipment19.price);
        System.out.println("Electric: " + equipment19.isElectric);

        GymEquipment equipment20 = new GymEquipment();
        equipment20.equipmentId = 20;
        equipment20.name = "Stepper Machine";
        equipment20.brand = "StepStrong";
        equipment20.category = "Cardio";
        equipment20.weight = 48.0;
        equipment20.price = 39000.0;
        equipment20.isElectric = true;
        System.out.println("=== Equipment 20 ===");
        System.out.println("ID: " + equipment20.equipmentId);
        System.out.println("Name: " + equipment20.name);
        System.out.println("Brand: " + equipment20.brand);
        System.out.println("Category: " + equipment20.category);
        System.out.println("Weight: " + equipment20.weight);
        System.out.println("Price: ₹" + equipment20.price);
        System.out.println("Electric: " + equipment20.isElectric);

        System.out.println("Main Ended");

		
    }
}
