class HatRunner {

    public static void main(String[] args) {

        System.out.println("Main Started");

        Hat hat1 = new Hat();
        hat1.hatId = 1;
        hat1.brand = "Nike";
        hat1.color = "Black";
        hat1.material = "Cotton";
        hat1.size = "M";
        hat1.style = "Baseball Cap";
        hat1.price = 799.0;
        System.out.println("=== Hat 1 ===");
        System.out.println("ID: " + hat1.hatId);
        System.out.println("Brand: " + hat1.brand);
        System.out.println("Color: " + hat1.color);
        System.out.println("Material: " + hat1.material);
        System.out.println("Size: " + hat1.size);
        System.out.println("Style: " + hat1.style);
        System.out.println("Price: ₹" + hat1.price);

        Hat hat2 = new Hat();
        hat2.hatId = 2;
        hat2.brand = "Adidas";
        hat2.color = "White";
        hat2.material = "Polyester";
        hat2.size = "L";
        hat2.style = "Snapback";
        hat2.price = 699.0;
        System.out.println("=== Hat 2 ===");
        System.out.println("ID: " + hat2.hatId);
        System.out.println("Brand: " + hat2.brand);
        System.out.println("Color: " + hat2.color);
        System.out.println("Material: " + hat2.material);
        System.out.println("Size: " + hat2.size);
        System.out.println("Style: " + hat2.style);
        System.out.println("Price: ₹" + hat2.price);

        Hat hat3 = new Hat();
        hat3.hatId = 3;
        hat3.brand = "Puma";
        hat3.color = "Grey";
        hat3.material = "Wool";
        hat3.size = "S";
        hat3.style = "Beanie";
        hat3.price = 499.0;
        System.out.println("=== Hat 3 ===");
        System.out.println("ID: " + hat3.hatId);
        System.out.println("Brand: " + hat3.brand);
        System.out.println("Color: " + hat3.color);
        System.out.println("Material: " + hat3.material);
        System.out.println("Size: " + hat3.size);
        System.out.println("Style: " + hat3.style);
        System.out.println("Price: ₹" + hat3.price);

        Hat hat4 = new Hat();
        hat4.hatId = 4;
        hat4.brand = "Levi's";
        hat4.color = "Blue";
        hat4.material = "Denim";
        hat4.size = "M";
        hat4.style = "Bucket Hat";
        hat4.price = 899.0;
        System.out.println("=== Hat 4 ===");
        System.out.println("ID: " + hat4.hatId);
        System.out.println("Brand: " + hat4.brand);
        System.out.println("Color: " + hat4.color);
        System.out.println("Material: " + hat4.material);
        System.out.println("Size: " + hat4.size);
        System.out.println("Style: " + hat4.style);
        System.out.println("Price: ₹" + hat4.price);

        Hat hat5 = new Hat();
        hat5.hatId = 5;
        hat5.brand = "H&M";
        hat5.color = "Brown";
        hat5.material = "Leather";
        hat5.size = "L";
        hat5.style = "Cowboy Hat";
        hat5.price = 1499.0;
        System.out.println("=== Hat 5 ===");
        System.out.println("ID: " + hat5.hatId);
        System.out.println("Brand: " + hat5.brand);
        System.out.println("Color: " + hat5.color);
        System.out.println("Material: " + hat5.material);
        System.out.println("Size: " + hat5.size);
        System.out.println("Style: " + hat5.style);
        System.out.println("Price: ₹" + hat5.price);

		Hat hat6 = new Hat();
        hat6.hatId = 6;
        hat6.brand = "Zara";
        hat6.color = "Olive";
        hat6.material = "Canvas";
        hat6.size = "S";
        hat6.style = "Fedora";
        hat6.price = 1099.0;
        System.out.println("=== Hat 6 ===");
        System.out.println("ID: " + hat6.hatId);
        System.out.println("Brand: " + hat6.brand);
        System.out.println("Color: " + hat6.color);
        System.out.println("Material: " + hat6.material);
        System.out.println("Size: " + hat6.size);
        System.out.println("Style: " + hat6.style);
        System.out.println("Price: ₹" + hat6.price);

        Hat hat7 = new Hat();
        hat7.hatId = 7;
        hat7.brand = "Allen Solly";
        hat7.color = "Green";
        hat7.material = "Linen";
        hat7.size = "M";
        hat7.style = "Panama";
        hat7.price = 999.0;
        System.out.println("=== Hat 7 ===");
        System.out.println("ID: " + hat7.hatId);
        System.out.println("Brand: " + hat7.brand);
        System.out.println("Color: " + hat7.color);
        System.out.println("Material: " + hat7.material);
        System.out.println("Size: " + hat7.size);
        System.out.println("Style: " + hat7.style);
        System.out.println("Price: ₹" + hat7.price);

        Hat hat8 = new Hat();
        hat8.hatId = 8;
        hat8.brand = "Gucci";
        hat8.color = "Red";
        hat8.material = "Wool";
        hat8.size = "L";
        hat8.style = "Newsboy";
        hat8.price = 2099.0;
        System.out.println("=== Hat 8 ===");
        System.out.println("ID: " + hat8.hatId);
        System.out.println("Brand: " + hat8.brand);
        System.out.println("Color: " + hat8.color);
        System.out.println("Material: " + hat8.material);
        System.out.println("Size: " + hat8.size);
        System.out.println("Style: " + hat8.style);
        System.out.println("Price: ₹" + hat8.price);

        Hat hat9 = new Hat();
        hat9.hatId = 9;
        hat9.brand = "Reebok";
        hat9.color = "Yellow";
        hat9.material = "Cotton";
        hat9.size = "M";
        hat9.style = "Flat Cap";
        hat9.price = 749.0;
        System.out.println("=== Hat 9 ===");
        System.out.println("ID: " + hat9.hatId);
        System.out.println("Brand: " + hat9.brand);
        System.out.println("Color: " + hat9.color);
        System.out.println("Material: " + hat9.material);
        System.out.println("Size: " + hat9.size);
        System.out.println("Style: " + hat9.style);
        System.out.println("Price: ₹" + hat9.price);

        Hat hat10 = new Hat();
        hat10.hatId = 10;
        hat10.brand = "Louis Vuitton";
        hat10.color = "Beige";
        hat10.material = "Felt";
        hat10.size = "S";
        hat10.style = "Bowler";
        hat10.price = 2999.0;
        System.out.println("=== Hat 10 ===");
        System.out.println("ID: " + hat10.hatId);
        System.out.println("Brand: " + hat10.brand);
        System.out.println("Color: " + hat10.color);
        System.out.println("Material: " + hat10.material);
        System.out.println("Size: " + hat10.size);
        System.out.println("Style: " + hat10.style);
        System.out.println("Price: ₹" + hat10.price);

        Hat hat11 = new Hat();
        hat11.hatId = 11;
        hat11.brand = "Diesel";
        hat11.color = "Navy";
        hat11.material = "Canvas";
        hat11.size = "M";
        hat11.style = "Military";
        hat11.price = 1250.0;
        System.out.println("=== Hat 11 ===");
        System.out.println("ID: " + hat11.hatId);
        System.out.println("Brand: " + hat11.brand);
        System.out.println("Color: " + hat11.color);
        System.out.println("Material: " + hat11.material);
        System.out.println("Size: " + hat11.size);
        System.out.println("Style: " + hat11.style);
        System.out.println("Price: ₹" + hat11.price);

        Hat hat12 = new Hat();
        hat12.hatId = 12;
        hat12.brand = "UCB";
        hat12.color = "Teal";
        hat12.material = "Wool";
        hat12.size = "L";
        hat12.style = "Trilby";
        hat12.price = 1350.0;
        System.out.println("=== Hat 12 ===");
        System.out.println("ID: " + hat12.hatId);
        System.out.println("Brand: " + hat12.brand);
        System.out.println("Color: " + hat12.color);
        System.out.println("Material: " + hat12.material);
        System.out.println("Size: " + hat12.size);
        System.out.println("Style: " + hat12.style);
        System.out.println("Price: ₹" + hat12.price);

        Hat hat13 = new Hat();
        hat13.hatId = 13;
        hat13.brand = "Fila";
        hat13.color = "Pink";
        hat13.material = "Felt";
        hat13.size = "S";
        hat13.style = "Beret";
        hat13.price = 849.0;
        System.out.println("=== Hat 13 ===");
        System.out.println("ID: " + hat13.hatId);
        System.out.println("Brand: " + hat13.brand);
        System.out.println("Color: " + hat13.color);
        System.out.println("Material: " + hat13.material);
        System.out.println("Size: " + hat13.size);
        System.out.println("Style: " + hat13.style);
        System.out.println("Price: ₹" + hat13.price);

        Hat hat14 = new Hat();
        hat14.hatId = 14;
        hat14.brand = "Armani";
        hat14.color = "Grey";
        hat14.material = "Silk";
        hat14.size = "M";
        hat14.style = "Top Hat";
        hat14.price = 3499.0;
        System.out.println("=== Hat 14 ===");
        System.out.println("ID: " + hat14.hatId);
        System.out.println("Brand: " + hat14.brand);
        System.out.println("Color: " + hat14.color);
        System.out.println("Material: " + hat14.material);
        System.out.println("Size: " + hat14.size);
        System.out.println("Style: " + hat14.style);
        System.out.println("Price: ₹" + hat14.price);

        Hat hat15 = new Hat();
        hat15.hatId = 15;
        hat15.brand = "Roadster";
        hat15.color = "Tan";
        hat15.material = "Leather";
        hat15.size = "L";
        hat15.style = "Cowboy";
        hat15.price = 1699.0;
        System.out.println("=== Hat 15 ===");
        System.out.println("ID: " + hat15.hatId);
        System.out.println("Brand: " + hat15.brand);
        System.out.println("Color: " + hat15.color);
        System.out.println("Material: " + hat15.material);
        System.out.println("Size: " + hat15.size);
        System.out.println("Style: " + hat15.style);
        System.out.println("Price: ₹" + hat15.price);

        Hat hat16 = new Hat();
        hat16.hatId = 16;
        hat16.brand = "Wrangler";
        hat16.color = "Charcoal";
        hat16.material = "Denim";
        hat16.size = "M";
        hat16.style = "Outback";
        hat16.price = 1199.0;
        System.out.println("=== Hat 16 ===");
        System.out.println("ID: " + hat16.hatId);
        System.out.println("Brand: " + hat16.brand);
        System.out.println("Color: " + hat16.color);
        System.out.println("Material: " + hat16.material);
        System.out.println("Size: " + hat16.size);
        System.out.println("Style: " + hat16.style);
        System.out.println("Price: ₹" + hat16.price);

        Hat hat17 = new Hat();
        hat17.hatId = 17;
        hat17.brand = "Spykar";
        hat17.color = "White";
        hat17.material = "Cotton";
        hat17.size = "S";
        hat17.style = "Golf Cap";
        hat17.price = 949.0;
        System.out.println("=== Hat 17 ===");
        System.out.println("ID: " + hat17.hatId);
        System.out.println("Brand: " + hat17.brand);
        System.out.println("Color: " + hat17.color);
        System.out.println("Material: " + hat17.material);
        System.out.println("Size: " + hat17.size);
        System.out.println("Style: " + hat17.style);
        System.out.println("Price: ₹" + hat17.price);

        Hat hat18 = new Hat();
        hat18.hatId = 18;
        hat18.brand = "Raymond";
        hat18.color = "Black";
        hat18.material = "Felt";
        hat18.size = "L";
        hat18.style = "Formal Hat";
        hat18.price = 1899.0;
        System.out.println("=== Hat 18 ===");
        System.out.println("ID: " + hat18.hatId);
        System.out.println("Brand: " + hat18.brand);
        System.out.println("Color: " + hat18.color);
        System.out.println("Material: " + hat18.material);
        System.out.println("Size: " + hat18.size);
        System.out.println("Style: " + hat18.style);
        System.out.println("Price: ₹" + hat18.price);

        Hat hat19 = new Hat();
        hat19.hatId = 19;
        hat19.brand = "Peter England";
        hat19.color = "Brown";
        hat19.material = "Canvas";
        hat19.size = "M";
        hat19.style = "Sun Hat";
        hat19.price = 1050.0;
        System.out.println("=== Hat 19 ===");
        System.out.println("ID: " + hat19.hatId);
        System.out.println("Brand: " + hat19.brand);
        System.out.println("Color: " + hat19.color);
        System.out.println("Material: " + hat19.material);
        System.out.println("Size: " + hat19.size);
        System.out.println("Style: " + hat19.style);
        System.out.println("Price: ₹" + hat19.price);

        Hat hat20 = new Hat();
        hat20.hatId = 20;
        hat20.brand = "Van Heusen";
        hat20.color = "Grey";
        hat20.material = "Linen";
        hat20.size = "L";
        hat20.style = "Flat Brim";
        hat20.price = 1399.0;
        System.out.println("=== Hat 20 ===");
        System.out.println("ID: " + hat20.hatId);
        System.out.println("Brand: " + hat20.brand);
        System.out.println("Color: " + hat20.color);
        System.out.println("Material: " + hat20.material);
        System.out.println("Size: " + hat20.size);
        System.out.println("Style: " + hat20.style);
        System.out.println("Price: ₹" + hat20.price);

        System.out.println("Main Ended");

    }
}
