class InvitationCardRunner {

    public static void main(String[] args) {

        System.out.println("Main Started");

        InvitationCard card1 = new InvitationCard();
        card1.cardId = 1;
        card1.eventType = "Wedding";
        card1.hostName = "Rahul & Anjali";
        card1.venue = "Taj West End, Bengaluru";
        card1.date = "25-12-2025";
        card1.time = "6:00 PM";
        card1.cardTheme = "Floral Gold";
        System.out.println("=== Invitation Card 1 ===");
        System.out.println("ID: " + card1.cardId);
        System.out.println("Event: " + card1.eventType);
        System.out.println("Host: " + card1.hostName);
        System.out.println("Venue: " + card1.venue);
        System.out.println("Date: " + card1.date);
        System.out.println("Time: " + card1.time);
        System.out.println("Theme: " + card1.cardTheme);

        InvitationCard card2 = new InvitationCard();
        card2.cardId = 2;
        card2.eventType = "Birthday";
        card2.hostName = "Aarav";
        card2.venue = "Wonderland Hall, Mumbai";
        card2.date = "15-08-2025";
        card2.time = "4:00 PM";
        card2.cardTheme = "Cartoon Theme";
        System.out.println("=== Invitation Card 2 ===");
        System.out.println("ID: " + card2.cardId);
        System.out.println("Event: " + card2.eventType);
        System.out.println("Host: " + card2.hostName);
        System.out.println("Venue: " + card2.venue);
        System.out.println("Date: " + card2.date);
        System.out.println("Time: " + card2.time);
        System.out.println("Theme: " + card2.cardTheme);

        InvitationCard card3 = new InvitationCard();
        card3.cardId = 3;
        card3.eventType = "Housewarming";
        card3.hostName = "Mr. & Mrs. Sharma";
        card3.venue = "Jayanagar, Bengaluru";
        card3.date = "01-11-2025";
        card3.time = "11:00 AM";
        card3.cardTheme = "Traditional Pooja";
        System.out.println("=== Invitation Card 3 ===");
        System.out.println("ID: " + card3.cardId);
        System.out.println("Event: " + card3.eventType);
        System.out.println("Host: " + card3.hostName);
        System.out.println("Venue: " + card3.venue);
        System.out.println("Date: " + card3.date);
        System.out.println("Time: " + card3.time);
        System.out.println("Theme: " + card3.cardTheme);

        InvitationCard card4 = new InvitationCard();
        card4.cardId = 4;
        card4.eventType = "Engagement";
        card4.hostName = "Karan & Priya";
        card4.venue = "Leela Palace, Delhi";
        card4.date = "18-09-2025";
        card4.time = "7:00 PM";
        card4.cardTheme = "Elegant Pastel";
        System.out.println("=== Invitation Card 4 ===");
        System.out.println("ID: " + card4.cardId);
        System.out.println("Event: " + card4.eventType);
        System.out.println("Host: " + card4.hostName);
        System.out.println("Venue: " + card4.venue);
        System.out.println("Date: " + card4.date);
        System.out.println("Time: " + card4.time);
        System.out.println("Theme: " + card4.cardTheme);

        InvitationCard card5 = new InvitationCard();
        card5.cardId = 5;
        card5.eventType = "Baby Shower";
        card5.hostName = "Megha";
        card5.venue = "JP Nagar, Bengaluru";
        card5.date = "05-10-2025";
        card5.time = "12:30 PM";
        card5.cardTheme = "Baby Blue & Pink";
        System.out.println("=== Invitation Card 5 ===");
        System.out.println("ID: " + card5.cardId);
        System.out.println("Event: " + card5.eventType);
        System.out.println("Host: " + card5.hostName);
        System.out.println("Venue: " + card5.venue);
        System.out.println("Date: " + card5.date);
        System.out.println("Time: " + card5.time);
        System.out.println("Theme: " + card5.cardTheme);

		InvitationCard card6 = new InvitationCard();
        card6.cardId = 6;
        card6.eventType = "Retirement";
        card6.hostName = "Mr. Ramesh Kumar";
        card6.venue = "Club House, Hyderabad";
        card6.date = "30-11-2025";
        card6.time = "5:00 PM";
        card6.cardTheme = "Golden Years";
        System.out.println("=== Invitation Card 6 ===");
        System.out.println("ID: " + card6.cardId);
        System.out.println("Event: " + card6.eventType);
        System.out.println("Host: " + card6.hostName);
        System.out.println("Venue: " + card6.venue);
        System.out.println("Date: " + card6.date);
        System.out.println("Time: " + card6.time);
        System.out.println("Theme: " + card6.cardTheme);

        InvitationCard card7 = new InvitationCard();
        card7.cardId = 7;
        card7.eventType = "Graduation";
        card7.hostName = "Neha Verma";
        card7.venue = "St. Xavier's Auditorium, Mumbai";
        card7.date = "10-06-2025";
        card7.time = "3:00 PM";
        card7.cardTheme = "Cap & Gown";
        System.out.println("=== Invitation Card 7 ===");
        System.out.println("ID: " + card7.cardId);
        System.out.println("Event: " + card7.eventType);
        System.out.println("Host: " + card7.hostName);
        System.out.println("Venue: " + card7.venue);
        System.out.println("Date: " + card7.date);
        System.out.println("Time: " + card7.time);
        System.out.println("Theme: " + card7.cardTheme);

        InvitationCard card8 = new InvitationCard();
        card8.cardId = 8;
        card8.eventType = "Anniversary";
        card8.hostName = "Ravi & Sita";
        card8.venue = "Marriott Hotel, Chennai";
        card8.date = "14-02-2025";
        card8.time = "8:00 PM";
        card8.cardTheme = "Romantic Red";
        System.out.println("=== Invitation Card 8 ===");
        System.out.println("ID: " + card8.cardId);
        System.out.println("Event: " + card8.eventType);
        System.out.println("Host: " + card8.hostName);
        System.out.println("Venue: " + card8.venue);
        System.out.println("Date: " + card8.date);
        System.out.println("Time: " + card8.time);
        System.out.println("Theme: " + card8.cardTheme);

        InvitationCard card9 = new InvitationCard();
        card9.cardId = 9;
        card9.eventType = "Naming Ceremony";
        card9.hostName = "The Patil Family";
        card9.venue = "Sankranti Hall, Pune";
        card9.date = "21-03-2025";
        card9.time = "10:00 AM";
        card9.cardTheme = "Traditional Baby";
        System.out.println("=== Invitation Card 9 ===");
        System.out.println("ID: " + card9.cardId);
        System.out.println("Event: " + card9.eventType);
        System.out.println("Host: " + card9.hostName);
        System.out.println("Venue: " + card9.venue);
        System.out.println("Date: " + card9.date);
        System.out.println("Time: " + card9.time);
        System.out.println("Theme: " + card9.cardTheme);

        InvitationCard card10 = new InvitationCard();
        card10.cardId = 10;
        card10.eventType = "Farewell";
        card10.hostName = "Class of 2025";
        card10.venue = "College Lawn, Bhopal";
        card10.date = "05-04-2025";
        card10.time = "6:30 PM";
        card10.cardTheme = "Memories & Laughter";
        System.out.println("=== Invitation Card 10 ===");
        System.out.println("ID: " + card10.cardId);
        System.out.println("Event: " + card10.eventType);
        System.out.println("Host: " + card10.hostName);
        System.out.println("Venue: " + card10.venue);
        System.out.println("Date: " + card10.date);
        System.out.println("Time: " + card10.time);
        System.out.println("Theme: " + card10.cardTheme);

        InvitationCard card11 = new InvitationCard();
        card11.cardId = 11;
        card11.eventType = "Reception";
        card11.hostName = "Deepak & Riya";
        card11.venue = "The Oberoi, Kolkata";
        card11.date = "28-12-2025";
        card11.time = "7:30 PM";
        card11.cardTheme = "Royal Purple";
        System.out.println("=== Invitation Card 11 ===");
        System.out.println("ID: " + card11.cardId);
        System.out.println("Event: " + card11.eventType);
        System.out.println("Host: " + card11.hostName);
        System.out.println("Venue: " + card11.venue);
        System.out.println("Date: " + card11.date);
        System.out.println("Time: " + card11.time);
        System.out.println("Theme: " + card11.cardTheme);

        InvitationCard card12 = new InvitationCard();
        card12.cardId = 12;
        card12.eventType = "Promotion Party";
        card12.hostName = "Mr. Arvind";
        card12.venue = "Company HQ, Gurgaon";
        card12.date = "07-05-2025";
        card12.time = "1:00 PM";
        card12.cardTheme = "Corporate Chic";
        System.out.println("=== Invitation Card 12 ===");
        System.out.println("ID: " + card12.cardId);
        System.out.println("Event: " + card12.eventType);
        System.out.println("Host: " + card12.hostName);
        System.out.println("Venue: " + card12.venue);
        System.out.println("Date: " + card12.date);
        System.out.println("Time: " + card12.time);
        System.out.println("Theme: " + card12.cardTheme);

        InvitationCard card13 = new InvitationCard();
        card13.cardId = 13;
        card13.eventType = "Sangeet";
        card13.hostName = "The Sharma Family";
        card13.venue = "Royal Orchid, Jaipur";
        card13.date = "12-01-2025";
        card13.time = "8:00 PM";
        card13.cardTheme = "Bollywood Night";
        System.out.println("=== Invitation Card 13 ===");
        System.out.println("ID: " + card13.cardId);
        System.out.println("Event: " + card13.eventType);
        System.out.println("Host: " + card13.hostName);
        System.out.println("Venue: " + card13.venue);
        System.out.println("Date: " + card13.date);
        System.out.println("Time: " + card13.time);
        System.out.println("Theme: " + card13.cardTheme);

        InvitationCard card14 = new InvitationCard();
        card14.cardId = 14;
        card14.eventType = "Bachelor Party";
        card14.hostName = "Kunal & Friends";
        card14.venue = "Beach Resort, Goa";
        card14.date = "09-03-2025";
        card14.time = "9:00 PM";
        card14.cardTheme = "Night Vibes";
        System.out.println("=== Invitation Card 14 ===");
        System.out.println("ID: " + card14.cardId);
        System.out.println("Event: " + card14.eventType);
        System.out.println("Host: " + card14.hostName);
        System.out.println("Venue: " + card14.venue);
        System.out.println("Date: " + card14.date);
        System.out.println("Time: " + card14.time);
        System.out.println("Theme: " + card14.cardTheme);

        InvitationCard card15 = new InvitationCard();
        card15.cardId = 15;
        card15.eventType = "Kitty Party";
        card15.hostName = "Neeta & Friends";
        card15.venue = "Palm Meadows, Mysore";
        card15.date = "19-09-2025";
        card15.time = "2:00 PM";
        card15.cardTheme = "Pink Garden";
        System.out.println("=== Invitation Card 15 ===");
        System.out.println("ID: " + card15.cardId);
        System.out.println("Event: " + card15.eventType);
        System.out.println("Host: " + card15.hostName);
        System.out.println("Venue: " + card15.venue);
        System.out.println("Date: " + card15.date);
        System.out.println("Time: " + card15.time);
        System.out.println("Theme: " + card15.cardTheme);

        InvitationCard card16 = new InvitationCard();
        card16.cardId = 16;
        card16.eventType = "Book Launch";
        card16.hostName = "Author: Pranav Desai";
        card16.venue = "Landmark Bookstore, Mumbai";
        card16.date = "03-07-2025";
        card16.time = "5:30 PM";
        card16.cardTheme = "Minimal Black & White";
        System.out.println("=== Invitation Card 16 ===");
        System.out.println("ID: " + card16.cardId);
        System.out.println("Event: " + card16.eventType);
        System.out.println("Host: " + card16.hostName);
        System.out.println("Venue: " + card16.venue);
        System.out.println("Date: " + card16.date);
        System.out.println("Time: " + card16.time);
        System.out.println("Theme: " + card16.cardTheme);

        InvitationCard card17 = new InvitationCard();
        card17.cardId = 17;
        card17.eventType = "New Year Party";
        card17.hostName = "The Mehta Family";
        card17.venue = "Rooftop Lounge, Surat";
        card17.date = "31-12-2025";
        card17.time = "10:00 PM";
        card17.cardTheme = "Sparkle & Shine";
        System.out.println("=== Invitation Card 17 ===");
        System.out.println("ID: " + card17.cardId);
        System.out.println("Event: " + card17.eventType);
        System.out.println("Host: " + card17.hostName);
        System.out.println("Venue: " + card17.venue);
        System.out.println("Date: " + card17.date);
        System.out.println("Time: " + card17.time);
        System.out.println("Theme: " + card17.cardTheme);

        InvitationCard card18 = new InvitationCard();
        card18.cardId = 18;
        card18.eventType = "Cradle Ceremony";
        card18.hostName = "The Rao Family";
        card18.venue = "Temple Hall, Vijayawada";
        card18.date = "08-08-2025";
        card18.time = "9:00 AM";
        card18.cardTheme = "Divine Baby Blue";
        System.out.println("=== Invitation Card 18 ===");
        System.out.println("ID: " + card18.cardId);
        System.out.println("Event: " + card18.eventType);
        System.out.println("Host: " + card18.hostName);
        System.out.println("Venue: " + card18.venue);
        System.out.println("Date: " + card18.date);
        System.out.println("Time: " + card18.time);
        System.out.println("Theme: " + card18.cardTheme);

        InvitationCard card19 = new InvitationCard();
        card19.cardId = 19;
        card19.eventType = "Baby Naming";
        card19.hostName = "Sowmya & Rakesh";
        card19.venue = "Home Lawn, Coimbatore";
        card19.date = "17-06-2025";
        card19.time = "10:30 AM";
        card19.cardTheme = "Soft Yellow Theme";
        System.out.println("=== Invitation Card 19 ===");
        System.out.println("ID: " + card19.cardId);
        System.out.println("Event: " + card19.eventType);
        System.out.println("Host: " + card19.hostName);
        System.out.println("Venue: " + card19.venue);
        System.out.println("Date: " + card19.date);
        System.out.println("Time: " + card19.time);
        System.out.println("Theme: " + card19.cardTheme);

        InvitationCard card20 = new InvitationCard();
        card20.cardId = 20;
        card20.eventType = "Corporate Dinner";
        card20.hostName = "TechNext Pvt Ltd";
        card20.venue = "ITC Gardenia, Bengaluru";
        card20.date = "29-09-2025";
        card20.time = "7:00 PM";
        card20.cardTheme = "Elegant Grey & Blue";
        System.out.println("=== Invitation Card 20 ===");
        System.out.println("ID: " + card20.cardId);
        System.out.println("Event: " + card20.eventType);
        System.out.println("Host: " + card20.hostName);
        System.out.println("Venue: " + card20.venue);
        System.out.println("Date: " + card20.date);
        System.out.println("Time: " + card20.time);
        System.out.println("Theme: " + card20.cardTheme);

        System.out.println("Main Ended");

		
    }
}
