class JewelleryRunner {

    public static void main(String[] args) {

        System.out.println("Main Started");

        Jewellery j1 = new Jewellery();
        j1.jewelleryId = 1;
        j1.type = "Necklace";
        j1.material = "Gold";
        j1.weight = 15.0;
        j1.brand = "Tanishq";
        j1.color = "Golden";
        j1.price = 75000.0;
        System.out.println("=== Jewellery 1 ===");
        System.out.println("ID: " + j1.jewelleryId);
        System.out.println("Type: " + j1.type);
        System.out.println("Material: " + j1.material);
        System.out.println("Weight: " + j1.weight + "g");
        System.out.println("Brand: " + j1.brand);
        System.out.println("Color: " + j1.color);
        System.out.println("Price: ₹" + j1.price);

        Jewellery j2 = new Jewellery();
        j2.jewelleryId = 2;
        j2.type = "Ring";
        j2.material = "Platinum";
        j2.weight = 5.0;
        j2.brand = "Malabar";
        j2.color = "Silver";
        j2.price = 35000.0;
        System.out.println("=== Jewellery 2 ===");
        System.out.println("ID: " + j2.jewelleryId);
        System.out.println("Type: " + j2.type);
        System.out.println("Material: " + j2.material);
        System.out.println("Weight: " + j2.weight + "g");
        System.out.println("Brand: " + j2.brand);
        System.out.println("Color: " + j2.color);
        System.out.println("Price: ₹" + j2.price);

        Jewellery j3 = new Jewellery();
        j3.jewelleryId = 3;
        j3.type = "Bangle";
        j3.material = "Gold";
        j3.weight = 10.0;
        j3.brand = "Kalyan";
        j3.color = "Yellow Gold";
        j3.price = 58000.0;
        System.out.println("=== Jewellery 3 ===");
        System.out.println("ID: " + j3.jewelleryId);
        System.out.println("Type: " + j3.type);
        System.out.println("Material: " + j3.material);
        System.out.println("Weight: " + j3.weight + "g");
        System.out.println("Brand: " + j3.brand);
        System.out.println("Color: " + j3.color);
        System.out.println("Price: ₹" + j3.price);

        Jewellery j4 = new Jewellery();
        j4.jewelleryId = 4;
        j4.type = "Earrings";
        j4.material = "Diamond";
        j4.weight = 3.5;
        j4.brand = "Reliance Jewels";
        j4.color = "White";
        j4.price = 45000.0;
        System.out.println("=== Jewellery 4 ===");
        System.out.println("ID: " + j4.jewelleryId);
        System.out.println("Type: " + j4.type);
        System.out.println("Material: " + j4.material);
        System.out.println("Weight: " + j4.weight + "g");
        System.out.println("Brand: " + j4.brand);
        System.out.println("Color: " + j4.color);
        System.out.println("Price: ₹" + j4.price);

        Jewellery j5 = new Jewellery();
        j5.jewelleryId = 5;
        j5.type = "Bracelet";
        j5.material = "Silver";
        j5.weight = 7.0;
        j5.brand = "PC Jeweller";
        j5.color = "Silver";
        j5.price = 8000.0;
        System.out.println("=== Jewellery 5 ===");
        System.out.println("ID: " + j5.jewelleryId);
        System.out.println("Type: " + j5.type);
        System.out.println("Material: " + j5.material);
        System.out.println("Weight: " + j5.weight + "g");
        System.out.println("Brand: " + j5.brand);
        System.out.println("Color: " + j5.color);
        System.out.println("Price: ₹" + j5.price);

		        Jewellery j6 = new Jewellery();
        j6.jewelleryId = 6;
        j6.type = "Pendant";
        j6.material = "Gold";
        j6.weight = 6.0;
        j6.brand = "Senco Gold";
        j6.color = "Golden";
        j6.price = 31000.0;
        System.out.println("=== Jewellery 6 ===");
        System.out.println("ID: " + j6.jewelleryId);
        System.out.println("Type: " + j6.type);
        System.out.println("Material: " + j6.material);
        System.out.println("Weight: " + j6.weight + "g");
        System.out.println("Brand: " + j6.brand);
        System.out.println("Color: " + j6.color);
        System.out.println("Price: ₹" + j6.price);

        Jewellery j7 = new Jewellery();
        j7.jewelleryId = 7;
        j7.type = "Anklet";
        j7.material = "Silver";
        j7.weight = 4.5;
        j7.brand = "Tribes India";
        j7.color = "Silver";
        j7.price = 2500.0;
        System.out.println("=== Jewellery 7 ===");
        System.out.println("ID: " + j7.jewelleryId);
        System.out.println("Type: " + j7.type);
        System.out.println("Material: " + j7.material);
        System.out.println("Weight: " + j7.weight + "g");
        System.out.println("Brand: " + j7.brand);
        System.out.println("Color: " + j7.color);
        System.out.println("Price: ₹" + j7.price);

        Jewellery j8 = new Jewellery();
        j8.jewelleryId = 8;
        j8.type = "Nose Pin";
        j8.material = "Diamond";
        j8.weight = 1.0;
        j8.brand = "CaratLane";
        j8.color = "White";
        j8.price = 15000.0;
        System.out.println("=== Jewellery 8 ===");
        System.out.println("ID: " + j8.jewelleryId);
        System.out.println("Type: " + j8.type);
        System.out.println("Material: " + j8.material);
        System.out.println("Weight: " + j8.weight + "g");
        System.out.println("Brand: " + j8.brand);
        System.out.println("Color: " + j8.color);
        System.out.println("Price: ₹" + j8.price);

        Jewellery j9 = new Jewellery();
        j9.jewelleryId = 9;
        j9.type = "Toe Ring";
        j9.material = "Silver";
        j9.weight = 2.0;
        j9.brand = "Local Craft";
        j9.color = "Silver";
        j9.price = 1000.0;
        System.out.println("=== Jewellery 9 ===");
        System.out.println("ID: " + j9.jewelleryId);
        System.out.println("Type: " + j9.type);
        System.out.println("Material: " + j9.material);
        System.out.println("Weight: " + j9.weight + "g");
        System.out.println("Brand: " + j9.brand);
        System.out.println("Color: " + j9.color);
        System.out.println("Price: ₹" + j9.price);

        Jewellery j10 = new Jewellery();
        j10.jewelleryId = 10;
        j10.type = "Mangalsutra";
        j10.material = "Gold";
        j10.weight = 18.0;
        j10.brand = "Kalyan Jewellers";
        j10.color = "Golden Black";
        j10.price = 82000.0;
        System.out.println("=== Jewellery 10 ===");
        System.out.println("ID: " + j10.jewelleryId);
        System.out.println("Type: " + j10.type);
        System.out.println("Material: " + j10.material);
        System.out.println("Weight: " + j10.weight + "g");
        System.out.println("Brand: " + j10.brand);
        System.out.println("Color: " + j10.color);
        System.out.println("Price: ₹" + j10.price);

        Jewellery j11 = new Jewellery();
        j11.jewelleryId = 11;
        j11.type = "Necklace";
        j11.material = "Diamond";
        j11.weight = 22.0;
        j11.brand = "Tanishq";
        j11.color = "White Gold";
        j11.price = 150000.0;
        System.out.println("=== Jewellery 11 ===");
        System.out.println("ID: " + j11.jewelleryId);
        System.out.println("Type: " + j11.type);
        System.out.println("Material: " + j11.material);
        System.out.println("Weight: " + j11.weight + "g");
        System.out.println("Brand: " + j11.brand);
        System.out.println("Color: " + j11.color);
        System.out.println("Price: ₹" + j11.price);

        Jewellery j12 = new Jewellery();
        j12.jewelleryId = 12;
        j12.type = "Ring";
        j12.material = "Gold";
        j12.weight = 4.0;
        j12.brand = "BlueStone";
        j12.color = "Golden";
        j12.price = 28000.0;
        System.out.println("=== Jewellery 12 ===");
        System.out.println("ID: " + j12.jewelleryId);
        System.out.println("Type: " + j12.type);
        System.out.println("Material: " + j12.material);
        System.out.println("Weight: " + j12.weight + "g");
        System.out.println("Brand: " + j12.brand);
        System.out.println("Color: " + j12.color);
        System.out.println("Price: ₹" + j12.price);

        Jewellery j13 = new Jewellery();
        j13.jewelleryId = 13;
        j13.type = "Bracelet";
        j13.material = "Gold";
        j13.weight = 8.0;
        j13.brand = "CaratLane";
        j13.color = "Golden";
        j13.price = 44000.0;
        System.out.println("=== Jewellery 13 ===");
        System.out.println("ID: " + j13.jewelleryId);
        System.out.println("Type: " + j13.type);
        System.out.println("Material: " + j13.material);
        System.out.println("Weight: " + j13.weight + "g");
        System.out.println("Brand: " + j13.brand);
        System.out.println("Color: " + j13.color);
        System.out.println("Price: ₹" + j13.price);

        Jewellery j14 = new Jewellery();
        j14.jewelleryId = 14;
        j14.type = "Earrings";
        j14.material = "Platinum";
        j14.weight = 6.5;
        j14.brand = "Malabar";
        j14.color = "Silver";
        j14.price = 56000.0;
        System.out.println("=== Jewellery 14 ===");
        System.out.println("ID: " + j14.jewelleryId);
        System.out.println("Type: " + j14.type);
        System.out.println("Material: " + j14.material);
        System.out.println("Weight: " + j14.weight + "g");
        System.out.println("Brand: " + j14.brand);
        System.out.println("Color: " + j14.color);
        System.out.println("Price: ₹" + j14.price);

        Jewellery j15 = new Jewellery();
        j15.jewelleryId = 15;
        j15.type = "Pendant";
        j15.material = "Silver";
        j15.weight = 5.5;
        j15.brand = "Local Maker";
        j15.color = "Silver";
        j15.price = 3200.0;
        System.out.println("=== Jewellery 15 ===");
        System.out.println("ID: " + j15.jewelleryId);
        System.out.println("Type: " + j15.type);
        System.out.println("Material: " + j15.material);
        System.out.println("Weight: " + j15.weight + "g");
        System.out.println("Brand: " + j15.brand);
        System.out.println("Color: " + j15.color);
        System.out.println("Price: ₹" + j15.price);

        Jewellery j16 = new Jewellery();
        j16.jewelleryId = 16;
        j16.type = "Ring";
        j16.material = "Diamond";
        j16.weight = 2.8;
        j16.brand = "Tanishq";
        j16.color = "White";
        j16.price = 62000.0;
        System.out.println("=== Jewellery 16 ===");
        System.out.println("ID: " + j16.jewelleryId);
        System.out.println("Type: " + j16.type);
        System.out.println("Material: " + j16.material);
        System.out.println("Weight: " + j16.weight + "g");
        System.out.println("Brand: " + j16.brand);
        System.out.println("Color: " + j16.color);
        System.out.println("Price: ₹" + j16.price);

        Jewellery j17 = new Jewellery();
        j17.jewelleryId = 17;
        j17.type = "Nose Pin";
        j17.material = "Gold";
        j17.weight = 1.2;
        j17.brand = "Malabar";
        j17.color = "Yellow Gold";
        j17.price = 7800.0;
        System.out.println("=== Jewellery 17 ===");
        System.out.println("ID: " + j17.jewelleryId);
        System.out.println("Type: " + j17.type);
        System.out.println("Material: " + j17.material);
        System.out.println("Weight: " + j17.weight + "g");
        System.out.println("Brand: " + j17.brand);
        System.out.println("Color: " + j17.color);
        System.out.println("Price: ₹" + j17.price);

        Jewellery j18 = new Jewellery();
        j18.jewelleryId = 18;
        j18.type = "Anklet";
        j18.material = "Silver";
        j18.weight = 4.0;
        j18.brand = "Tribal Art";
        j18.color = "Silver";
        j18.price = 1800.0;
        System.out.println("=== Jewellery 18 ===");
        System.out.println("ID: " + j18.jewelleryId);
        System.out.println("Type: " + j18.type);
        System.out.println("Material: " + j18.material);
        System.out.println("Weight: " + j18.weight + "g");
        System.out.println("Brand: " + j18.brand);
        System.out.println("Color: " + j18.color);
        System.out.println("Price: ₹" + j18.price);

        Jewellery j19 = new Jewellery();
        j19.jewelleryId = 19;
        j19.type = "Necklace";
        j19.material = "Gold";
        j19.weight = 25.0;
        j19.brand = "Senco Gold";
        j19.color = "Golden";
        j19.price = 102000.0;
        System.out.println("=== Jewellery 19 ===");
        System.out.println("ID: " + j19.jewelleryId);
        System.out.println("Type: " + j19.type);
        System.out.println("Material: " + j19.material);
        System.out.println("Weight: " + j19.weight + "g");
        System.out.println("Brand: " + j19.brand);
        System.out.println("Color: " + j19.color);
        System.out.println("Price: ₹" + j19.price);

        Jewellery j20 = new Jewellery();
        j20.jewelleryId = 20;
        j20.type = "Bracelet";
        j20.material = "Platinum";
        j20.weight = 10.0;
        j20.brand = "BlueStone";
        j20.color = "Silver";
        j20.price = 70000.0;
        System.out.println("=== Jewellery 20 ===");
        System.out.println("ID: " + j20.jewelleryId);
        System.out.println("Type: " + j20.type);
        System.out.println("Material: " + j20.material);
        System.out.println("Weight: " + j20.weight + "g");
        System.out.println("Brand: " + j20.brand);
        System.out.println("Color: " + j20.color);
        System.out.println("Price: ₹" + j20.price);

        System.out.println("Main Ended");

    }
}
