class RodRunner {

    public static void main(String[] args) {

        System.out.println("Main Started");

        Rod r1 = new Rod();
        r1.rodId = 1;
        r1.material = "Iron";
        r1.lengthInMeters = 2.5;
        r1.weightInKg = 5.0;
        r1.usage = "Construction";
        r1.manufacturer = "Tata Steel";
        r1.price = 1500.0;
        System.out.println("=== Rod 1 ===");
        System.out.println("ID: " + r1.rodId);
        System.out.println("Material: " + r1.material);
        System.out.println("Length: " + r1.lengthInMeters + " meters");
        System.out.println("Weight: " + r1.weightInKg + " kg");
        System.out.println("Usage: " + r1.usage);
        System.out.println("Manufacturer: " + r1.manufacturer);
        System.out.println("Price: ₹" + r1.price);

        Rod r2 = new Rod();
        r2.rodId = 2;
        r2.material = "Steel";
        r2.lengthInMeters = 3.0;
        r2.weightInKg = 6.5;
        r2.usage = "Fencing";
        r2.manufacturer = "JSW Steel";
        r2.price = 1800.0;
        System.out.println("=== Rod 2 ===");
        System.out.println("ID: " + r2.rodId);
        System.out.println("Material: " + r2.material);
        System.out.println("Length: " + r2.lengthInMeters + " meters");
        System.out.println("Weight: " + r2.weightInKg + " kg");
        System.out.println("Usage: " + r2.usage);
        System.out.println("Manufacturer: " + r2.manufacturer);
        System.out.println("Price: ₹" + r2.price);

        Rod r3 = new Rod();
        r3.rodId = 3;
        r3.material = "Aluminum";
        r3.lengthInMeters = 2.0;
        r3.weightInKg = 2.8;
        r3.usage = "Curtain Rod";
        r3.manufacturer = "Hindalco";
        r3.price = 1000.0;
        System.out.println("=== Rod 3 ===");
        System.out.println("ID: " + r3.rodId);
        System.out.println("Material: " + r3.material);
        System.out.println("Length: " + r3.lengthInMeters + " meters");
        System.out.println("Weight: " + r3.weightInKg + " kg");
        System.out.println("Usage: " + r3.usage);
        System.out.println("Manufacturer: " + r3.manufacturer);
        System.out.println("Price: ₹" + r3.price);

        Rod r4 = new Rod();
        r4.rodId = 4;
        r4.material = "Fiberglass";
        r4.lengthInMeters = 1.8;
        r4.weightInKg = 1.2;
        r4.usage = "Fishing";
        r4.manufacturer = "Shimano";
        r4.price = 2200.0;
        System.out.println("=== Rod 4 ===");
        System.out.println("ID: " + r4.rodId);
        System.out.println("Material: " + r4.material);
        System.out.println("Length: " + r4.lengthInMeters + " meters");
        System.out.println("Weight: " + r4.weightInKg + " kg");
        System.out.println("Usage: " + r4.usage);
        System.out.println("Manufacturer: " + r4.manufacturer);
        System.out.println("Price: ₹" + r4.price);

        Rod r5 = new Rod();
        r5.rodId = 5;
        r5.material = "PVC";
        r5.lengthInMeters = 2.2;
        r5.weightInKg = 1.5;
        r5.usage = "Plumbing";
        r5.manufacturer = "Astral Pipes";
        r5.price = 600.0;
        System.out.println("=== Rod 5 ===");
        System.out.println("ID: " + r5.rodId);
        System.out.println("Material: " + r5.material);
        System.out.println("Length: " + r5.lengthInMeters + " meters");
        System.out.println("Weight: " + r5.weightInKg + " kg");
        System.out.println("Usage: " + r5.usage);
        System.out.println("Manufacturer: " + r5.manufacturer);
        System.out.println("Price: ₹" + r5.price);

		        Rod r6 = new Rod();
        r6.rodId = 6;
        r6.material = "Carbon Fiber";
        r6.lengthInMeters = 1.5;
        r6.weightInKg = 1.0;
        r6.usage = "Camera Rig";
        r6.manufacturer = "Manfrotto";
        r6.price = 3500.0;
        System.out.println("=== Rod 6 ===");
        System.out.println("ID: " + r6.rodId);
        System.out.println("Material: " + r6.material);
        System.out.println("Length: " + r6.lengthInMeters + " meters");
        System.out.println("Weight: " + r6.weightInKg + " kg");
        System.out.println("Usage: " + r6.usage);
        System.out.println("Manufacturer: " + r6.manufacturer);
        System.out.println("Price: ₹" + r6.price);

        Rod r7 = new Rod();
        r7.rodId = 7;
        r7.material = "Brass";
        r7.lengthInMeters = 2.3;
        r7.weightInKg = 4.3;
        r7.usage = "Decorative";
        r7.manufacturer = "RoyalMetals";
        r7.price = 2000.0;
        System.out.println("=== Rod 7 ===");
        System.out.println("ID: " + r7.rodId);
        System.out.println("Material: " + r7.material);
        System.out.println("Length: " + r7.lengthInMeters + " meters");
        System.out.println("Weight: " + r7.weightInKg + " kg");
        System.out.println("Usage: " + r7.usage);
        System.out.println("Manufacturer: " + r7.manufacturer);
        System.out.println("Price: ₹" + r7.price);

        Rod r8 = new Rod();
        r8.rodId = 8;
        r8.material = "Titanium";
        r8.lengthInMeters = 1.6;
        r8.weightInKg = 2.0;
        r8.usage = "Aerospace";
        r8.manufacturer = "Titanium Inc.";
        r8.price = 9500.0;
        System.out.println("=== Rod 8 ===");
        System.out.println("ID: " + r8.rodId);
        System.out.println("Material: " + r8.material);
        System.out.println("Length: " + r8.lengthInMeters + " meters");
        System.out.println("Weight: " + r8.weightInKg + " kg");
        System.out.println("Usage: " + r8.usage);
        System.out.println("Manufacturer: " + r8.manufacturer);
        System.out.println("Price: ₹" + r8.price);

        Rod r9 = new Rod();
        r9.rodId = 9;
        r9.material = "Copper";
        r9.lengthInMeters = 2.1;
        r9.weightInKg = 3.6;
        r9.usage = "Electrical";
        r9.manufacturer = "Vedanta";
        r9.price = 3100.0;
        System.out.println("=== Rod 9 ===");
        System.out.println("ID: " + r9.rodId);
        System.out.println("Material: " + r9.material);
        System.out.println("Length: " + r9.lengthInMeters + " meters");
        System.out.println("Weight: " + r9.weightInKg + " kg");
        System.out.println("Usage: " + r9.usage);
        System.out.println("Manufacturer: " + r9.manufacturer);
        System.out.println("Price: ₹" + r9.price);

        Rod r10 = new Rod();
        r10.rodId = 10;
        r10.material = "Graphite";
        r10.lengthInMeters = 1.4;
        r10.weightInKg = 0.9;
        r10.usage = "Sport Equipment";
        r10.manufacturer = "Wilson";
        r10.price = 2800.0;
        System.out.println("=== Rod 10 ===");
        System.out.println("ID: " + r10.rodId);
        System.out.println("Material: " + r10.material);
        System.out.println("Length: " + r10.lengthInMeters + " meters");
        System.out.println("Weight: " + r10.weightInKg + " kg");
        System.out.println("Usage: " + r10.usage);
        System.out.println("Manufacturer: " + r10.manufacturer);
        System.out.println("Price: ₹" + r10.price);

        Rod r11 = new Rod();
        r11.rodId = 11;
        r11.material = "Bamboo";
        r11.lengthInMeters = 2.0;
        r11.weightInKg = 1.1;
        r11.usage = "Support Stick";
        r11.manufacturer = "EcoBuild";
        r11.price = 500.0;
        System.out.println("=== Rod 11 ===");
        System.out.println("ID: " + r11.rodId);
        System.out.println("Material: " + r11.material);
        System.out.println("Length: " + r11.lengthInMeters + " meters");
        System.out.println("Weight: " + r11.weightInKg + " kg");
        System.out.println("Usage: " + r11.usage);
        System.out.println("Manufacturer: " + r11.manufacturer);
        System.out.println("Price: ₹" + r11.price);

        Rod r12 = new Rod();
        r12.rodId = 12;
        r12.material = "Plastic";
        r12.lengthInMeters = 2.0;
        r12.weightInKg = 1.3;
        r12.usage = "DIY Projects";
        r12.manufacturer = "PlasticTech";
        r12.price = 300.0;
        System.out.println("=== Rod 12 ===");
        System.out.println("ID: " + r12.rodId);
        System.out.println("Material: " + r12.material);
        System.out.println("Length: " + r12.lengthInMeters + " meters");
        System.out.println("Weight: " + r12.weightInKg + " kg");
        System.out.println("Usage: " + r12.usage);
        System.out.println("Manufacturer: " + r12.manufacturer);
        System.out.println("Price: ₹" + r12.price);

        Rod r13 = new Rod();
        r13.rodId = 13;
        r13.material = "Glass";
        r13.lengthInMeters = 1.9;
        r13.weightInKg = 2.1;
        r13.usage = "Art & Decor";
        r13.manufacturer = "GlassArt";
        r13.price = 1300.0;
        System.out.println("=== Rod 13 ===");
        System.out.println("ID: " + r13.rodId);
        System.out.println("Material: " + r13.material);
        System.out.println("Length: " + r13.lengthInMeters + " meters");
        System.out.println("Weight: " + r13.weightInKg + " kg");
        System.out.println("Usage: " + r13.usage);
        System.out.println("Manufacturer: " + r13.manufacturer);
        System.out.println("Price: ₹" + r13.price);

        Rod r14 = new Rod();
        r14.rodId = 14;
        r14.material = "Chrome";
        r14.lengthInMeters = 2.0;
        r14.weightInKg = 4.2;
        r14.usage = "Furniture Frame";
        r14.manufacturer = "FurniTech";
        r14.price = 1600.0;
        System.out.println("=== Rod 14 ===");
        System.out.println("ID: " + r14.rodId);
        System.out.println("Material: " + r14.material);
        System.out.println("Length: " + r14.lengthInMeters + " meters");
        System.out.println("Weight: " + r14.weightInKg + " kg");
        System.out.println("Usage: " + r14.usage);
        System.out.println("Manufacturer: " + r14.manufacturer);
        System.out.println("Price: ₹" + r14.price);

        Rod r15 = new Rod();
        r15.rodId = 15;
        r15.material = "Zinc";
        r15.lengthInMeters = 1.7;
        r15.weightInKg = 2.5;
        r15.usage = "Industrial Use";
        r15.manufacturer = "MetalWorks";
        r15.price = 1100.0;
        System.out.println("=== Rod 15 ===");
        System.out.println("ID: " + r15.rodId);
        System.out.println("Material: " + r15.material);
        System.out.println("Length: " + r15.lengthInMeters + " meters");
        System.out.println("Weight: " + r15.weightInKg + " kg");
        System.out.println("Usage: " + r15.usage);
        System.out.println("Manufacturer: " + r15.manufacturer);
        System.out.println("Price: ₹" + r15.price);

        Rod r16 = new Rod();
        r16.rodId = 16;
        r16.material = "Nickel";
        r16.lengthInMeters = 2.0;
        r16.weightInKg = 2.9;
        r16.usage = "Chemical Plants";
        r16.manufacturer = "NickelPro";
        r16.price = 4500.0;
        System.out.println("=== Rod 16 ===");
        System.out.println("ID: " + r16.rodId);
        System.out.println("Material: " + r16.material);
        System.out.println("Length: " + r16.lengthInMeters + " meters");
        System.out.println("Weight: " + r16.weightInKg + " kg");
        System.out.println("Usage: " + r16.usage);
        System.out.println("Manufacturer: " + r16.manufacturer);
        System.out.println("Price: ₹" + r16.price);

        Rod r17 = new Rod();
        r17.rodId = 17;
        r17.material = "Stainless Steel";
        r17.lengthInMeters = 2.4;
        r17.weightInKg = 3.8;
        r17.usage = "Kitchenware";
        r17.manufacturer = "SteelKing";
        r17.price = 2400.0;
        System.out.println("=== Rod 17 ===");
        System.out.println("ID: " + r17.rodId);
        System.out.println("Material: " + r17.material);
        System.out.println("Length: " + r17.lengthInMeters + " meters");
        System.out.println("Weight: " + r17.weightInKg + " kg");
        System.out.println("Usage: " + r17.usage);
        System.out.println("Manufacturer: " + r17.manufacturer);
        System.out.println("Price: ₹" + r17.price);

        Rod r18 = new Rod();
        r18.rodId = 18;
        r18.material = "Lead";
        r18.lengthInMeters = 1.2;
        r18.weightInKg = 6.0;
        r18.usage = "Radiation Shield";
        r18.manufacturer = "LeadSafe";
        r18.price = 6000.0;
        System.out.println("=== Rod 18 ===");
        System.out.println("ID: " + r18.rodId);
        System.out.println("Material: " + r18.material);
        System.out.println("Length: " + r18.lengthInMeters + " meters");
        System.out.println("Weight: " + r18.weightInKg + " kg");
        System.out.println("Usage: " + r18.usage);
        System.out.println("Manufacturer: " + r18.manufacturer);
        System.out.println("Price: ₹" + r18.price);

        Rod r19 = new Rod();
        r19.rodId = 19;
        r19.material = "Rubber";
        r19.lengthInMeters = 1.5;
        r19.weightInKg = 2.0;
        r19.usage = "Grips";
        r19.manufacturer = "GripTech";
        r19.price = 800.0;
        System.out.println("=== Rod 19 ===");
        System.out.println("ID: " + r19.rodId);
        System.out.println("Material: " + r19.material);
        System.out.println("Length: " + r19.lengthInMeters + " meters");
        System.out.println("Weight: " + r19.weightInKg + " kg");
        System.out.println("Usage: " + r19.usage);
        System.out.println("Manufacturer: " + r19.manufacturer);
        System.out.println("Price: ₹" + r19.price);

        Rod r20 = new Rod();
        r20.rodId = 20;
        r20.material = "Steel Alloy";
        r20.lengthInMeters = 2.6;
        r20.weightInKg = 4.8;
        r20.usage = "Machine Parts";
        r20.manufacturer = "MetalForge";
        r20.price = 3800.0;
        System.out.println("=== Rod 20 ===");
        System.out.println("ID: " + r20.rodId);
        System.out.println("Material: " + r20.material);
        System.out.println("Length: " + r20.lengthInMeters + " meters");
        System.out.println("Weight: " + r20.weightInKg + " kg");
        System.out.println("Usage: " + r20.usage);
        System.out.println("Manufacturer: " + r20.manufacturer);
        System.out.println("Price: ₹" + r20.price);

        System.out.println("Main Ended");
    }
}
